server:
  port: 8081
spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://config-service:8888"
  cloud:
    gateway:
      routes:
        - id: websocket-worker
          uri: ws://websocket-worker:8094
          predicates:
            - Path=/ws/**
        - id: user-identity-service
          uri: lb://USER-IDENTITY-SERVICE
          predicates:
            - Path=/api/v1/auth/**
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true
